# Generated by Django 5.2.17 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("status", models.CharField(max_length=32)),
                ("response_payload", models.JSONField()),
                ("is_public", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="qa_records", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="questionrecord",
            index=models.Index(fields=["owner", "-created_at"], name="portal_qa_owner_recent"),
        ),
        migrations.AddIndex(
            model_name="questionrecord",
            index=models.Index(fields=["is_public", "-published_at"], name="portal_qa_public_recent"),
        ),
    ]
